export const APP_SHELL_DOMAIN_CONTEXT_NAMES = [
  "runtimeThreadContext",
  "sessionIdentityContext",
  "workspaceCatalogContext",
  "gitSurfaceContext",
  "modeRoutingContext",
  "accountSurfaceContext",
  "workspaceNavigationContext",
  "composerContext",
  "layoutContext",
  "fileEditorContext",
  "settingsContext",
  "threadDataContext",
  "runtimeContext",
  "modelSelectionContext",
  "collaborationModeContext",
] as const;

export type AppShellDomainContextName =
  (typeof APP_SHELL_DOMAIN_CONTEXT_NAMES)[number];

export type AppShellDomainContextValue = Record<string, unknown>;

export type AppShellDomainContexts = {
  runtimeThreadContext: AppShellDomainContextValue;
  sessionIdentityContext: AppShellDomainContextValue;
  workspaceCatalogContext: AppShellDomainContextValue;
  gitSurfaceContext: AppShellDomainContextValue;
  modeRoutingContext: AppShellDomainContextValue;
  accountSurfaceContext: AppShellDomainContextValue;
  workspaceNavigationContext: AppShellDomainContextValue;
  composerContext: AppShellDomainContextValue;
  layoutContext: AppShellDomainContextValue;
  fileEditorContext: AppShellDomainContextValue;
  settingsContext: AppShellDomainContextValue;
  threadDataContext: AppShellDomainContextValue;
  runtimeContext: AppShellDomainContextValue;
  modelSelectionContext: AppShellDomainContextValue;
  collaborationModeContext: AppShellDomainContextValue;
};

export type AppShellDomainContextSelection<
  TDomainName extends AppShellDomainContextName,
> = Pick<AppShellDomainContexts, TDomainName>;

export const APP_SHELL_DOMAIN_CONTEXT_OWNED_KEYS: Record<
  AppShellDomainContextName,
  readonly string[]
> = {
  runtimeThreadContext: [
    "runtimeThreadBoundary",
    // S4 PR-D：turn 级 conversation bags（从 settingsContext 迁入；
    // 读侧仅 layoutNodes，其订阅全 15 域，迁移不改变其可读性）
    "historyLoadingByThreadId",
    "historyLoadingProgressByThreadId",
    "historyRestoredAtMsByThread",
    "threadListCursorByWorkspace",
    "threadListPagingByWorkspace",
    "threadParentById",
    // S4 bag-split PR-1：会话热路径（从 workspaceNavigation / settings 迁入）
    "activeItems",
    "activePlan",
    "activeRateLimits",
    "activeTokenUsage",
    "activeTurnId",
    "canInterrupt",
    "isProcessing",
    "isReviewing",
    "timelinePlan",
    // S4 PR-C：conversation UI（rename/delete prompt / copy / hydration）与
    // review-prompt 流程（preset / branch / commit 选择）——读侧仅 layoutNodes
    // （从 composerContext / workspaceNavigationContext 归位）
    "choosePreset",
    "handleCopyThread",
    "handleDeleteThreadPromptCancel",
    "handleDeleteThreadPromptConfirm",
    "handleRenamePromptCancel",
    "handleRenamePromptChange",
    "handleRenamePromptConfirm",
    "handleRenameThread",
    "handleReviewPromptKeyDown",
    "handleSelectCommit",
    "handleSelectStatusPanelSubagent",
    "highlightedBranchIndex",
    "highlightedCommitIndex",
    "highlightedPresetIndex",
    "hydratedThreadListWorkspaceIds",
    "isDeleteThreadPromptBusy",
    // S4 PR-E：thread 级动作与 review/highlight setters（从 settings/layout 归位；读侧仅 layoutNodes）
    "isThreadAutoNaming",
    "isThreadPinned",
    "listThreadsForWorkspaceTracked",
    "loadOlderThreadsForWorkspace",
    "openDeleteThreadPrompt",
    "pinThread",
    "pinnedThreadsVersion",
    "refreshThread",
    "renamePrompt",
    "setHighlightedBranchIndex",
    "setHighlightedCommitIndex",
    "setHighlightedPresetIndex",
    "showPresetStep",
    "startCompact",
    "toggleCompletionEmailIntent",
    "triggerAutoThreadTitle",
    "unpinThread",
    "updateCustomInstructions",
    "userInputRequests",
  ],
  sessionIdentityContext: [
    "RECENT_THREAD_LIMIT",
    "activeParentWorkspace",
    "activePath",
    "activeThreadId",
    "activeThreadIdForModeRef",
    "activeThreadIdRef",
    "activeWorkspace",
    "activeWorkspaceId",
    "activeWorkspaceIdRef",
    "activeWorkspaceRef",
    "activeWorkspaceThreads",
    "baseWorkspaceRef",
    // S4 PR-E：identity setters 与 state 同域（从 settings 归位）
    "setActiveThreadId",
    "setActiveWorkspaceId",
  ],
  workspaceCatalogContext: [
    "addCloneAgent",
    "addWorkspace",
    "addWorkspaceFromPath",
    "addWorktreeAgent",
    "assignWorkspaceGroup",
    "cancelClonePrompt",
    "cancelWorktreePrompt",
    "chooseCloneCopiesFolder",
    "clearCloneCopiesFolder",
    "clonePrompt",
    "closeWorktreeCreateResult",
    "confirmClonePrompt",
    "confirmRenameWorktreeUpstream",
    "confirmWorktreePrompt",
    "connectWorkspace",
    "createWorkspaceGroup",
    "deleteWorkspaceGroup",
    "deletingWorktreeIds",
    "directories",
    "directoryMetadata",
    "ensureWorkspaceThreadListLoaded",
    "forkClaudeSessionFromMessageForWorkspace",
    "forkSessionFromMessageForWorkspace",
    "forkThreadForWorkspace",
    "getWorkspaceGroupName",
    "getWorkspacePromptsDir",
    // S4 PR-C：workspace/agent 入口与拖放 intake（从 composerContext 归位）
    "groupedWorkspaces",
    "handleAddAgent",
    "handleAddCloneAgent",
    "handleAddWorkspace",
    "handleAddWorktreeAgent",
    "handleArchiveActiveThread",
    "handleEnsureWorkspaceThreadsForSettings",
    "handleOpenNewWindow",
    "handleWorkspaceDragEnter",
    "handleWorkspaceDragLeave",
    "handleWorkspaceDragOver",
    "handleWorkspaceDrop",
    "isMultiRepository",
    "repositories",
    "repositoriesLoading",
    // S4 PR-E：worktree/clone/workspace 设置与目录态（从 settings/layout/gitSurface 归位）
    "gitignoredDirectories",
    "gitignoredFiles",
    "homeWorkspaceSelectedId",
    "isWorkspaceDropActive",
    "isWorktreeWorkspace",
    "launchScriptState",
    "launchScriptsState",
    "moveWorkspaceGroup",
    "removeWorkspace",
    "removeWorktree",
    "renameWorkspaceGroup",
    "setWorkspaceHomeWorkspaceId",
    "ungroupedLabel",
    "updateCloneCopyName",
    "updateWorkspaceCodexBin",
    "updateWorkspaceSettings",
    "updateWorktreeBaseRef",
    "updateWorktreeBranch",
    "updateWorktreePublishToOrigin",
    "updateWorktreeSetupScript",
    "useSuggestedCloneCopiesFolder",
    "workspaceGroups",
    "workspaces",
    "workspacesById",
    "workspacesByPath",
    "worktreeApplyError",
    "worktreeApplyLoading",
    "worktreeApplySuccess",
    "worktreeCreateResult",
    "worktreeLabel",
    "worktreePrompt",
    "worktreeRename",
  ],
  gitSurfaceContext: [
    "GitHubPanelData",
    "activeDiffError",
    "activeDiffLoading",
    "activeDiffs",
    "activeGitRoot",
    "activeGitHistoryTabId",
    "branchError",
    "branches",
    "clearGitOperationErrors",
    "commitError",
    "commitLoading",
    "commitMessage",
    "commitMessageError",
    "commitMessageLoading",
    "confirmBranch",
    "confirmCommit",
    "currentBranch",
    "diffScrollRequestId",
    "diffSource",
    "fileStatus",
    "gitDiffListView",
    "gitDiffViewStyle",
    "gitHistoryPanelHeight",
    "gitIssues",
    "gitIssuesError",
    "gitIssuesLoading",
    "gitIssuesTotal",
    "gitLogAhead",
    "gitLogAheadEntries",
    "gitLogBehind",
    "gitLogBehindEntries",
    "gitLogEntries",
    "gitLogError",
    "gitLogLoading",
    "gitLogTotal",
    "gitLogUpstream",
    "gitPanelMode",
    "gitPullRequestComments",
    "gitPullRequestCommentsError",
    "gitPullRequestCommentsLoading",
    "gitPullRequests",
    "gitPullRequestsError",
    "gitPullRequestsLoading",
    "gitPullRequestsTotal",
    "gitRemoteUrl",
    "gitRootCandidates",
    "gitRootScanDepth",
    "gitRootScanError",
    "gitRootScanHasScanned",
    "gitRootScanLoading",
    "gitStatus",
    // S4 PR-C：git 操作 handlers 从 composerContext 归位（含 GitHub panel 变更回调）
    "handleActivateGitHistoryTab",
    "handleActiveDiffPath",
    "handleApplyWorktreeChanges",
    "handleCheckoutBranch",
    "handleCommit",
    "handleCommitAndPush",
    "handleCommitAndSync",
    "handleCommitMessageChange",
    "handleCreateBranch",
    "handleGenerateCommitMessage",
    "handleGitIssuesChange",
    "handleGitPanelModeChange",
    "handleGitPullRequestCommentsChange",
    "handleGitPullRequestDiffsChange",
    "handleGitPullRequestsChange",
    "handlePickGitRoot",
    "handlePush",
    "handleRevertAllGitChanges",
    "handleRevertGitFile",
    "handleRevertGitPaths",
    "handleSetGitRoot",
    "handleStageGitAll",
    "handleStageGitFile",
    "handleSync",
    "handleUnstageGitAll",
    "handleUnstageGitFile",
    "handleUnstageGitPaths",
    "handleUpdateBranch",
    "handleUpdateAllRepositories",
    "handleCheckoutAllRepositories",
    "handleLoadCommonRepositoryBranches",
    "localBranches",
    "remoteBranches",
    "repositoryError",
    "repositoryStatuses",
    "repositoryStatusesLoading",
    "refreshRepositoryStatuses",
    "handleStageRepositoryFile",
    "handleUnstageRepositoryFile",
    "handleUnstageRepositoryAll",
    "handleUnstageRepositoryFiles",
    "handleRevertRepositoryFile",
    "handleRevertRepositoryFiles",
    "handleStageRepositoryAll",
    "handleCommitRepositories",
    "repositoryCommitSummary",
    "selectRepository",
    "selectedRepositoryRoot",
    // S4 PR-E：git state setters 与刷新动作（从 settings/layout 归位）
    "queueGitStatusRefresh",
    "refreshGitDiffs",
    "refreshGitLog",
    "setGitDiffListView",
    "setGitDiffViewStyle",
    "setGitRootScanDepth",
    // S4 PR-E：删 7 个无 bag 读者 keys（checkoutBranch/createBranch/clearGitRootCandidates/gitCommitDiffs/gitHistoryPanelHeightRef/gitPullRequestDiffsError/gitPullRequestDiffsLoading；根层直传不经 bag）
    // S4 PR-F：再删 3 个无 bag 读者 keys（gitPullRequestDiffs/setDiffSource/setGitPanelMode；search 段经 searchAndComposerInput 直传，不经 bag）
  ],
  modeRoutingContext: [
    "accessMode",
    "activeTab",
    "appMode",
    "centerMode",
    "claudeAccessModeRef",
    "filePanelMode",
    // S4 PR-C：UI 模式/面板路由与环境标志（从 composerContext 归位）
    "handleAppModeChange",
    "handleDebugClick",
    "handleLockPanel",
    "handleResolvedClaudeThinkingVisibleChange",
    "handleToggleRuntimeConsole",
    "handleToggleTerminalPanel",
    "handleUnlockPanel",
    "hasActivePlan",
    "isCompact",
    "isMacDesktop",
    "isPanelLocked",
    "isPhone",
    "isSearchPaletteOpen",
    // S4 PR-E：mode/surface 路由 setters 与环境标志（从 settings/layout/gitSurface 归位）
    "exitDiffView",
    "isTablet",
    "isWindowsDesktop",
    "setActiveTab",
    "setAppMode",
    "setCenterMode",
    "setFilePanelMode",
    "setHomeOpen",
    "setIsSearchPaletteOpen",
    "showExtensions",
    "showGitHistory",
    "showHome",
    "showWorkspaceHome",
  ],
  accountSurfaceContext: [
    "accountByWorkspace",
    "accountSwitching",
    "activeAccount",
    "approvals",
    // S4 PR-C：账号切换 / 审批 / 邮件会话入口（从 composerContext 归位）
    "handleApprovalBatchAccept",
    "handleApprovalDecision",
    "handleApprovalRemember",
    "handleCancelSwitchAccount",
    "handleOpenMailSession",
    "handleSwitchAccount",
    // S4 PR-E：账号 rate limit 刷新（从 layout 归位）
    "refreshAccountRateLimits",
  ],
  workspaceNavigationContext: [
    "SettingsView",
    "activeEditorFilePath",
    "activeEditorLineRange",
    "activeEngine",
    "fileCompareSession",
    "fileHistoryTabs",
    "activeRenamePrompt",
    "agentTaskScrollRequest",
    "activeTerminalId",
    "addDebugEntry",
    "alertError",
    "appRootRef",
    "appSettings",
    "appSettingsLoading",
    "claudeThinkingVisible",
    "clearDebugEntries",
    "clearDraftForThread",
    "closePlanPanel",
    "checkForUpdates",
    "closeReleaseNotes",
    "closeReviewPrompt",
    "closeSettings",
    "closeTerminalPanel",
    "collapseRightPanel",
    "collapseSidebar",
    "commands",
    "completionEmailIntentByThread",
    "completionTrackerBySessionRef",
    "completionTrackerReadyRef",
    "confirmCustom",
    "createPrompt",
    "debugEntries",
    "debugOpen",
    "debugPanelHeight",
    "deletePrompt",
    "deleteThreadPrompt",
    "dismissErrorToast",
    "dismissUpdate",
    "doctor",
    "claudeDoctor",
    "kimiDoctor",
    "grokDoctor",
    "opencodeDoctor",
    "piDoctor",
    "ompDoctor",
    "qoderDoctor",
    "editorHighlightTarget",
    "editorNavigationTarget",
    "editorSplitCompanion",
    "editorSplitLayout",
    "engineModelsAsOptions",
    "engineSelectedModelIdByType",
    "engineStatuses",
    "ensureLaunchTerminal",
    "ensureTerminalWithTitle",
    "errorToasts",
    "expandRightPanel",
    "expandSidebar",
    "fileReferenceMode",
    "fileTreeLoadError",
    "fileTreeSourceVersion",
    "files",
    "getGlobalPromptsDir",
    "getPinTimestamp",
    "getThreadRows",
    "globalSearchFilesByWorkspace",
    // S4 PR-C：debug/updater 动作（从 composerContext 归位）
    "handleCopyDebug",
    "handleTestNotificationSound",
    // S4 PR-E：editor/appSettings setters 与 releaseNotes 态（从 settings/layout 归位）
    "openReleaseNotes",
    "releaseNotesActiveIndex",
    "releaseNotesEntries",
    "releaseNotesError",
    "releaseNotesLoading",
    "releaseNotesOpen",
    "setActiveEditorLineRange",
    "setActiveEngine",
    "setAppSettings",
    "setEditorSplitCompanion",
    "setEditorSplitLayout",
    "setFileReferenceMode",
  ],
  composerContext: [
    // S4 PR-C：composer 域瘦身（141 → 39）。只保留 composer 输入面真正消费的
    // 字段：draft/queue/images/prefill/insert 输入态 + 发送与队列 handlers +
    // prompts 库 + agent/access-mode 选择 + interruptTurn。
    "activeFusingMessageId",
    "activeImages",
    "activeQueue",
    "activeQueuedHandoffBubble",
    "attachImages",
    "canFuseActiveQueue",
    "composerEditorSettings",
    "composerInputRef",
    "composerInsert",
    "fuseDisabledReasonKey",
    "handleCreatePrompt",
    "handleDeletePrompt",
    "handleDeleteQueued",
    "handleDraftChange",
    "handleEditQueued",
    "handleExitPlanModeExecute",
    "handleFuseQueued",
    "handleInsertComposerText",
    "handleMovePrompt",
    "handleRevealGeneralPrompts",
    "handleRevealWorkspacePrompts",
    "handleSelectAgent",
    "handleSendPrompt",
    "handleSendPromptToNewAgent",
    "handleSetAccessMode",
    "handleUpdatePrompt",
    "handleUserInputSubmit",
    "handleUserInputSubmitWithPlanApply",
    "interruptTurn",
    "isPlanMode",
    "isPlanPanelDismissed",
    "onTextareaHeightChange",
    "pickImages",
    "prefillDraft",
    "removeImage",
    "setComposerInsert",
    "setPrefillDraft",
    "skills",
    "textareaHeight",
    // S4 PR-E：prompts 库与 composer 选择持久化（从 layout 归位）
    "persistComposerSelectionForThread",
    "prompts",
  ],
  layoutContext: [
    "liveEditPreviewEnabled",
    "lockLiveSessions",
    "models",
    "handleOpenClaudeTui",
    "normalizePath",
    "onCloseTerminal",
    "onDebugPanelResizeStart",
    "onGitHistoryPanelResizeStart",
    "onNewTerminal",
    "onPlanPanelResizeStart",
    "onRightPanelResizeStart",
    "onSelectTerminal",
    "onSidebarResizeStart",
    "onTerminalPanelResizeStart",
    "openAppIconById",
    "openCodeAgents",
    "openPlanPanel",
    "planPanelHeight",
    "pushError",
    "pushLoading",
    "queueSaveSettings",
    "recentThreads",
    "reduceTransparency",
    "windowTransparencyEnabled",
    "windowOpacity",
    "refreshFiles",
    "removeImagesForThread",
    "removeThread",
    "removeThreads",
    // S4 PR-E：layout 态 setters 与 releaseNotes 翻页（从 settings 归位）
    "setLiveEditPreviewEnabled",
    "setReduceTransparency",
    "setWindowOpacity",
    "setWindowTransparencyEnabled",
    "showNextReleaseNotes",
    "showPreviousReleaseNotes",
    // S4 PR-E：删 20 个无 bag 读者 keys（根层直传不经 bag）
  ],
  fileEditorContext: [
    // S4 PR-C：文件 tab / editor / compare / file-history 动作（从 composerContext 归位）
    "handleActivateFileTab",
    "handleCloseAllFileHistories",
    "handleCloseAllFileTabs",
    "handleCloseFileCompare",
    "handleCloseFileHistory",
    "handleCloseFileTab",
    "handleCloseOtherFileHistories",
    "handleCloseOtherFileTabs",
    "handleExitEditor",
    "handleOpenDetachedFileExplorer",
    "handleOpenFile",
    "handleOpenFileHistory",
    "handleOpenScratchFileCompare",
    "handleOpenWorkspaceFileCompare",
    "handleReorderFileTabs",
    "handleSelectDiff",
    "handleSelectOpenAppId",
    "isEditorFileMaximized",
    "isFilesLoading",
    "renameWorktreeUpstream",
    "renameWorktreeUpstreamPrompt",
    "resetGitHubPanelState",
    "resetSoloSplitToHalf",
    "resetWorkspaceThreads",
    "resolveCloneProjectContext",
    "resolveCanonicalThreadId",
    "resolveComposerSelectionForThread",
    "resolveOpenCodeAgentForThread",
    "resolveOpenCodeVariantForThread",
    "restartTerminalSession",
    "retryReleaseNotesLoad",
    "reviewPrompt",
    "rightPanelCollapsed",
    "rightPanelWidth",
    "scaleShortcutText",
    "scaleShortcutTitle",
    "scanGitRoots",
    "searchContentFilters",
    "searchApiHydrationStatus",
    "searchFileHydrationStatus",
    "searchPaletteQuery",
    "searchPaletteSelectedIndex",
    "searchResults",
    "searchScope",
    "selectBranch",
    "selectBranchAtIndex",
    "selectCommit",
    "selectCommitAtIndex",
    "selectHome",
    "selectWorkspace",
    "selectedAgent",
    "selectedCommitSha",
    "selectedDiffPath",
    "selectedAgentRef",
    "selectedOpenCodeAgent",
    "selectedOpenCodeVariant",
    "selectedPullRequest",
    // S4 PR-E：file/search/选择 setters 与 openFileTabs（从 settings/layout 归位）
    "openFileTabs",
    "setIsEditorFileMaximized",
    "setSearchContentFilters",
    "setSearchPaletteQuery",
    "setSearchPaletteSelectedIndex",
    "setSearchScope",
    "setSelectedCommitSha",
    "setSelectedDiffPath",
    "setSelectedPullRequest",
  ],
  settingsContext: [
    "sendUserMessageToThread",
    "settingsHighlightTarget",
    "settingsOpen",
    "settingsSection",
    "loadingProgressDialog",
    "dismissLoadingProgressDialog",
    "shouldLoadDiffs",
    "shouldLoadGitHubPanelData",
    "showLoadingProgressDialog",
    "hideLoadingProgressDialog",
    "showDebugButton",
    "sidebarCollapsed",
    "sidebarWidth",
    "startThreadForWorkspace",
    "startSharedSessionForWorkspace",
    "startUpdate",
    "syncError",
    "syncLoading",
    "t",
    "tabletTab",
    "terminalOpen",
    "terminalPanelHeight",
    "terminalState",
    "terminalTabs",
    "updaterState",
    "workspaceActivity",
    "workspaceDropTargetRef",
    "sessionRadarRunningSessions",
    "sessionRadarRecentCompletedSessions",
    "runningSessionCountByWorkspaceId",
    "recentCompletedSessionCountByWorkspaceId",
    // S4 PR-E：openSettings 归位 settings 域（从 layout）
    "openSettings",
    // S4 PR-E：删 17 个无 bag 读者 keys（根层直传不经 bag）
  ],
  // F5（fix-session-switch-jank-red-lines）：threads 全量 map 从 settingsContext
  // 迁入独立 threadDataContext（ownership matrix 性能红线）。冷域 bag 不再因线程
  // dispatch 失效；消费集见 APP_SHELL_CONSUMER_DOMAIN_SELECTION。
  threadDataContext: [
    "threadItemsByThread",
    "threadListLoadingByWorkspace",
    "threadStatusById",
    "threadsByWorkspace",
  ],
  runtimeContext: [
    "runtimeRunState",
  ],
  modelSelectionContext: [
    "effectiveModels",
    "effectiveReasoningSupported",
    "effectiveSelectedModel",
    "effectiveSelectedModelId",
    "providerModelCatalogs",
    "reasoningOptions",
    "reasoningSupported",
    "refreshEngineModels",
    "resolvedEffort",
    "resolvedModel",
    "selectedEffort",
    "selectedModelId",
    "setSelectedEffort",
    "setSelectedModelId",
    // S4 PR-C：模型/engine 选择动作（从 composerContext 归位）
    "availableEngines",
    "handleOpenModelSettings",
    "handleRefreshModelConfig",
    "handleSelectModel",
    "handleSelectOpenCodeAgent",
    "handleSelectOpenCodeVariant",
    "isModelConfigRefreshing",
    // S4 PR-E：engine 刷新（从 layout 归位）
    "refreshEngines",
  ],
  collaborationModeContext: [
    "applySelectedCollaborationMode",
    "collaborationModePayload",
    "collaborationModes",
    "collaborationModesEnabled",
    "collaborationRuntimeModeByThread",
    "collaborationUiModeByThread",
    "handleCollaborationModeResolved",
    "resolveCollaborationRuntimeMode",
    "resolveCollaborationUiMode",
    "selectedCollaborationMode",
    "selectedCollaborationModeId",
    "setCodexCollaborationMode",
    "setCollaborationRuntimeModeByThread",
    "setCollaborationUiModeByThread",
    "setSelectedCollaborationModeId",
  ],
};

export function listAppShellDomainContextNames(): AppShellDomainContextName[] {
  return [...APP_SHELL_DOMAIN_CONTEXT_NAMES];
}

export function defineAppShellDomainContexts<T extends AppShellDomainContexts>(
  contexts: T,
): T {
  return contexts;
}

/** 导出各 consumer 的 domain 选择集，供边界测试锁定，防止回潮成「全量 flatten」。 */
export const APP_SHELL_CONSUMER_DOMAIN_SELECTION = {
  // S4 PR-C：runtimeContext（runtimeRunState）由 layoutNodes 直读
  // input.appShellDomainContexts.runtimeContext，不经 bag flatten，故移出选择集
  // 三刀后续：layoutNodes 按 zone 拆 bag，热域变化不再重建 chrome/git flatten。
  layoutNodes: [
    "runtimeThreadContext",
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "workspaceNavigationContext",
    "composerContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
    // F5：threads 全量 map 显式消费（sidebar/topbar 投影真实读者）
    "threadDataContext",
    "modelSelectionContext",
    "collaborationModeContext",
  ],
  layoutNodesCanvas: [
    "runtimeThreadContext",
    "sessionIdentityContext",
    "composerContext",
    "modelSelectionContext",
    "collaborationModeContext",
    // F5：threads 全量 map 随侧栏节点构建走 canvas zone bag（与 runtimeThread 热域
    // 同区）；chrome zone 不再因线程 dispatch 重建。
    "threadDataContext",
  ],
  layoutNodesChrome: [
    "workspaceCatalogContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "workspaceNavigationContext",
    "layoutContext",
    "settingsContext",
  ],
  layoutNodesGit: [
    "gitSurfaceContext",
    "fileEditorContext",
  ],
  sections: [
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "workspaceNavigationContext",
    "composerContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
    // F5：threads 全量 map 显式消费（flows/radar/quickSwitcher 真实读者；
    // 4b 深化时按消费点逐一投影化收窄并更新红线 gate）
    "threadDataContext",
  ],
  // S4 PR-C：render 不再读 composerContext（原读取的 keys 已全部归位到
  // gitSurface / fileEditor / modeRouting / accountSurface / workspaceCatalog /
  // workspaceNavigation；输入态 activeImages/activeQueue/prefillDraft 等归
  // composerContext 后只扇出 sections/layoutNodes，render 不再被输入路径打到）
  render: [
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "workspaceNavigationContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
    // F5：threads 全量 map 显式消费（当前仅 Settings 的 workspace 数据管理
    // 读 threadsByWorkspace/threadListLoadingByWorkspace；4b 应改由 settings
    // surface 窄通道供给后移出本选择集并更新红线 gate）
    "threadDataContext",
    "runtimeContext",
  ],
} as const satisfies Record<string, readonly AppShellDomainContextName[]>;

function areAppShellDomainContextValuesShallowEqual(
  left: AppShellDomainContextValue,
  right: AppShellDomainContextValue,
): boolean {
  if (Object.is(left, right)) {
    return true;
  }
  const leftKeys = Object.keys(left);
  const rightKeys = Object.keys(right);
  if (leftKeys.length !== rightKeys.length) {
    return false;
  }
  return leftKeys.every((key) => Object.is(left[key], right[key]));
}

export function reuseStableAppShellDomainContexts(
  previousContexts: AppShellDomainContexts | null | undefined,
  nextContexts: AppShellDomainContexts,
): AppShellDomainContexts {
  if (!previousContexts) {
    return nextContexts;
  }
  const stable = {} as AppShellDomainContexts;
  let changed = false;
  for (const domainName of APP_SHELL_DOMAIN_CONTEXT_NAMES) {
    const stableDomain = areAppShellDomainContextValuesShallowEqual(
      previousContexts[domainName],
      nextContexts[domainName],
    )
      ? previousContexts[domainName]
      : nextContexts[domainName];
    stable[domainName] = stableDomain;
    changed ||= stableDomain !== previousContexts[domainName];
  }
  // Domain values may all be stable even when the assembly hook itself reruns
  // (for example, a sibling Host publishes an unrelated field). Preserve the
  // outer bag identity too; otherwise every rerun defeats React memo/deferred
  // boundaries and rebuilds the entire shell for a no-op snapshot.
  return changed ? stable : previousContexts;
}

export function findOverlappingAppShellDomainKeys(): string[] {
  const keyOwners = new Map<string, AppShellDomainContextName>();
  const overlappingKeys = new Set<string>();
  for (const domainName of APP_SHELL_DOMAIN_CONTEXT_NAMES) {
    for (const key of APP_SHELL_DOMAIN_CONTEXT_OWNED_KEYS[domainName]) {
      const previousOwner = keyOwners.get(key);
      if (previousOwner && previousOwner !== domainName) {
        overlappingKeys.add(key);
      } else {
        keyOwners.set(key, domainName);
      }
    }
  }
  return [...overlappingKeys].sort();
}
