// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    appearance: {
      "motionPaused": "System reduced motion is active. Select On and save to play the effect.",
      "motionOn": "On",
      "motionSystem": "Follow system",
      "motionOff": "Off",
      "cancel": "Cancel changes",
      "customize": "Home appearance",
      "description": "Make this space yours. Leave the title empty to use the default.",
      "title": "Title",
      "font": "Title style",
      "system": "System",
      "serif": "Serif",
      "mono": "Monospace",
      "logo": "Custom logo",
      "logoHint": "PNG, JPEG or WebP · up to 512 KB and 2048 × 2048. Stored locally.",
      "engineLogo": "Use engine logo",
      "loading": "Loading image…",
      "logoError": "Choose a valid PNG, JPEG or WebP under 512 KB and 2048 × 2048.",
      "particles": "Particle effect",
      "density": "Particle density",
      "dense": "Dense",
      "balanced": "Balanced",
      "sparse": "Sparse",
      "color": "Particle color",
      "theme": "Follow theme",
      "customColor": "Custom color",
      "motionHint": "Move the pointer over the title and logo to scatter particles; move away to restore them. On overrides system reduced motion.",
      "reset": "Reset defaults",
      "apply": "Save"
    },
    "badge": "Chat inicial com reconhecimento de workspace",
    "minimalTitle": "Crie qualquer coisa",
    "announcementTag": "Novo",
    "announcementText": "Explore templates de landing, cartões de fluxo de trabalho e prompts iniciais",
    "announcementAction": "Descobrir",
    "title": "Agent ccgui, torne o trabalho mais fácil",
    "titleLineOne": "Pressione Enter",
    "titleLineTwo": "Crie Apps Mais Rápido",
    "subtitle": "Mantenha o compositor que você já conhece, adicione um ritmo de início mais forte ao redor dele e avance para a execução real com menos atrito de configuração.",
    "promptPlaceholder": "Descreva seu objetivo, por exemplo: Gerar notas de lançamento para este repositório e incluir verificações de risco.",
    "pathResolving": "Resolvendo o caminho padrão do projeto...",
    "workspaceSearchPlaceholder": "Buscar projetos",
    "addWorkspaceAction": "Adicionar novo projeto",
    "workspaceNoMatch": "Nenhum projeto encontrado",
    "loadingRecentAgents": "Carregando trabalho recente",
    "recentConversations": "Conversas recentes",
    "quickActions": "Ações rápidas",
    "placeholderHint": "Estes pontos de entrada são espaços reservados visuais por enquanto.",
    "placeholderSelected": "{{label}} em breve.",
    "seeAll": "Ver tudo",
    "navPrev": "Cartões anteriores",
    "navNext": "Próximos cartões",
    "comingSoon": "Em breve",
    "tabs": {
      "templates": "Templates",
      "workflows": "Fluxos de trabalho"
    },
    "quick": {
      "plan": "Planejar a partir do briefing",
      "doc": "Docs",
      "release": "Notas de lançamento",
      "review": "Revisar repositório",
      "spec": "Rascunhar spec"
    },
    "cards": {
      "website": {
        "title": "Kit de Lançamento de Site",
        "description": "Layout de hero, estrutura e texto inicial para uma página de lançamento bem-acabada."
      },
      "creator": {
        "title": "Painel do Criador",
        "description": "Uma central de controle focada em analytics para conteúdo, tráfego e prompts."
      },
      "audio": {
        "title": "Landing de Áudio",
        "description": "Gradientes suaves e métricas marcantes para lançamentos de música, podcasts ou mídia."
      },
      "editorial": {
        "title": "Manifesto Editorial",
        "description": "Tipografia estilo pôster para campanhas, declarações e vitrines de marca."
      },
      "release": {
        "title": "Checklist de Lançamento",
        "description": "Uma entrega em etapas para alterações, verificação, notas e acompanhamento do rollout."
      },
      "research": {
        "title": "Sprint de Pesquisa",
        "description": "Reúna perguntas, colete achados de fontes e sintetize-os em próximas ações."
      },
      "debug": {
        "title": "Central de Depuração",
        "description": "Triando logs, restringindo regressões e documentando correções verificadas."
      },
      "content": {
        "title": "Pipeline de Conteúdo",
        "description": "Briefing, rascunho, revisão e publicação com checkpoints consistentes."
      }
    }
  }
};

export default homeChat;
