import { GitHubPanelData, SettingsView } from "../render/lazyViews";
import { useMemo } from "react";
import { useAppShellDomainAssembly } from "../domains/useAppShellDomainAssembly";
import { useMemoizedRuntimeThreadProviderValue } from "../domains/runtimeThreadProvider";
import { useMemoizedComposerProviderValue } from "../domains/composerProvider";
import { useMemoizedLayoutChromeProviderValue } from "../domains/layoutChromeProvider";
import {
  CATALOG_FIELDS,
  COMPOSER_FIELDS,
  FLOWS_FIELDS,
  GIT_FIELDS,
  RUNTIME_FIELDS,
  SESSION_FIELDS,
} from "./appShellAssemblyHostFields";
import { useHostFields } from "./appShellHostBus";

const EMPTY_HOST_SECTION: Readonly<Record<string, unknown>> = Object.freeze({});

function mergeHostSlices(
  ...slices: Array<Record<string, unknown>>
): Record<string, unknown> {
  return Object.assign({}, ...slices);
}

/**
 * 刀 3：只做 bag / zone value 装配，不再跑业务 hooks。
 * 禁止全量 snapshot 订阅：任意 Host 切片一变就会重跑整棵视图。
 */
export function useAppShellAssemblyHost() {
  const session = useHostFields("session", SESSION_FIELDS);
  const catalog = useHostFields("catalog", CATALOG_FIELDS);
  const git = useHostFields("git", GIT_FIELDS);
  const runtime = useHostFields("runtime", RUNTIME_FIELDS);
  const composer = useHostFields("composer", COMPOSER_FIELDS);
  const flows = useHostFields("flows", FLOWS_FIELDS);
  const merged = mergeHostSlices(session, catalog, git, runtime, composer, flows);
  const sessionRadarFeed = (flows.sessionRadarFeed ?? {}) as Record<string, unknown>;

  const appShellDomainContexts = useAppShellDomainAssembly({
    runtimeThreadBoundary: merged.runtimeThreadBoundary,
    activeItems: merged.activeItems,
    activePlan: merged.activePlan,
    activeRateLimits: merged.activeRateLimits,
    activeTokenUsage: merged.activeTokenUsage,
    activeTurnId: merged.activeTurnId,
    canInterrupt: merged.canInterrupt,
    isProcessing: merged.isProcessing,
    isReviewing: merged.isReviewing,
    timelinePlan: merged.timelinePlan,
    RECENT_THREAD_LIMIT: merged.RECENT_THREAD_LIMIT,
    accessMode: merged.accessMode,
    accountByWorkspace: merged.accountByWorkspace,
    accountSwitching: merged.accountSwitching,
    activeAccount: merged.activeAccount,
    activeDiffError: merged.activeDiffError,
    activeDiffLoading: merged.activeDiffLoading,
    activeDiffs: merged.activeDiffs,
    activeEditorFilePath: merged.activeEditorFilePath,
    activeEditorLineRange: merged.activeEditorLineRange,
    activeEngine: merged.activeEngine,
    activeGitRoot: merged.activeGitRoot,
    activeImages: merged.activeImages,
    activeFusingMessageId: merged.activeFusingMessageId,
    fileCompareSession: merged.fileCompareSession,
    fileHistoryTabs: merged.fileHistoryTabs,
    activeGitHistoryTabId: merged.activeGitHistoryTabId,
    activeParentWorkspace: merged.activeParentWorkspace,
    activePath: merged.activePath,
    activeQueue: merged.activeQueue,
    activeQueuedHandoffBubble: merged.activeQueuedHandoffBubble,
    activeRenamePrompt: merged.activeRenamePrompt,
    activeTab: merged.activeTab,
    agentTaskScrollRequest: merged.agentTaskScrollRequest,
    activeTerminalId: merged.activeTerminalId,
    activeThreadId: merged.activeThreadId,
    activeThreadIdForModeRef: merged.activeThreadIdForModeRef,
    activeThreadIdRef: merged.activeThreadIdRef,
    activeWorkspace: merged.activeWorkspace,
    activeWorkspaceId: merged.activeWorkspaceId,
    activeWorkspaceIdRef: merged.activeWorkspaceIdRef,
    activeWorkspaceRef: merged.activeWorkspaceRef,
    activeWorkspaceThreads: merged.activeWorkspaceThreads,
    addCloneAgent: merged.addCloneAgent,
    addDebugEntry: merged.addDebugEntry,
    addWorkspace: merged.addWorkspace,
    addWorkspaceFromPath: merged.addWorkspaceFromPath,
    addWorktreeAgent: merged.addWorktreeAgent,
    alertError: merged.alertError,
    appMode: merged.appMode,
    appRootRef: merged.appRootRef,
    appSettings: merged.appSettings,
    appSettingsLoading: merged.appSettingsLoading,
    approvals: merged.approvals,
    assignWorkspaceGroup: merged.assignWorkspaceGroup,
    attachImages: merged.attachImages,
    baseWorkspaceRef: merged.baseWorkspaceRef,
    branches: merged.branches,
    branchError: merged.branchError,
    currentBranch: merged.currentBranch,
    localBranches: merged.localBranches,
    remoteBranches: merged.remoteBranches,
    repositories: merged.repositories,
    repositoriesLoading: merged.repositoriesLoading,
    repositoryError: merged.repositoryError,
    repositoryStatuses: merged.repositoryStatuses,
    repositoryStatusesLoading: merged.repositoryStatusesLoading,
    isMultiRepository: merged.isMultiRepository,
    refreshRepositoryStatuses: merged.refreshRepositoryStatuses,
    handleStageRepositoryFile: merged.handleStageRepositoryFile,
    handleUnstageRepositoryFile: merged.handleUnstageRepositoryFile,
    handleUnstageRepositoryAll: merged.handleUnstageRepositoryAll,
    handleUnstageRepositoryFiles: merged.handleUnstageRepositoryFiles,
    handleRevertRepositoryFile: merged.handleRevertRepositoryFile,
    handleRevertRepositoryFiles: merged.handleRevertRepositoryFiles,
    handleStageRepositoryAll: merged.handleStageRepositoryAll,
    handleCommitRepositories: merged.handleCommitRepositories,
    repositoryCommitSummary: merged.repositoryCommitSummary,
    selectedRepositoryRoot: merged.selectedRepositoryRoot,
    selectRepository: merged.selectRepository,
    canFuseActiveQueue: merged.canFuseActiveQueue,
    fuseDisabledReasonKey: merged.fuseDisabledReasonKey,
    cancelClonePrompt: merged.cancelClonePrompt,
    cancelWorktreePrompt: merged.cancelWorktreePrompt,
    centerMode: merged.centerMode,
    chooseCloneCopiesFolder: merged.chooseCloneCopiesFolder,
    choosePreset: merged.choosePreset,
    claudeAccessModeRef: merged.claudeAccessModeRef,
    claudeThinkingVisible: merged.claudeThinkingVisible,
    clearCloneCopiesFolder: merged.clearCloneCopiesFolder,
    clearDebugEntries: merged.clearDebugEntries,
    clearDraftForThread: merged.clearDraftForThread,
    clearGitOperationErrors: merged.clearGitOperationErrors,
    checkForUpdates: merged.checkForUpdates,
    clonePrompt: merged.clonePrompt,
    closePlanPanel: merged.closePlanPanel,
    closeReleaseNotes: merged.closeReleaseNotes,
    closeReviewPrompt: merged.closeReviewPrompt,
    closeSettings: merged.closeSettings,
    closeTerminalPanel: merged.closeTerminalPanel,
    closeWorktreeCreateResult: merged.closeWorktreeCreateResult,
    collapseRightPanel: merged.collapseRightPanel,
    collapseSidebar: merged.collapseSidebar,
    commands: merged.commands,
    commitError: merged.commitError,
    commitLoading: merged.commitLoading,
    commitMessage: merged.commitMessage,
    commitMessageError: merged.commitMessageError,
    commitMessageLoading: merged.commitMessageLoading,
    completionEmailIntentByThread: merged.completionEmailIntentByThread,
    completionTrackerBySessionRef: merged.completionTrackerBySessionRef,
    completionTrackerReadyRef: merged.completionTrackerReadyRef,
    composerEditorSettings: merged.composerEditorSettings,
    composerInputRef: merged.composerInputRef,
    composerInsert: merged.composerInsert,
    confirmBranch: merged.confirmBranch,
    confirmClonePrompt: merged.confirmClonePrompt,
    confirmCommit: merged.confirmCommit,
    confirmCustom: merged.confirmCustom,
    confirmRenameWorktreeUpstream: merged.confirmRenameWorktreeUpstream,
    confirmWorktreePrompt: merged.confirmWorktreePrompt,
    connectWorkspace: merged.connectWorkspace,
    createPrompt: merged.createPrompt,
    createWorkspaceGroup: merged.createWorkspaceGroup,
    debugEntries: merged.debugEntries,
    debugOpen: merged.debugOpen,
    debugPanelHeight: merged.debugPanelHeight,
    deletePrompt: merged.deletePrompt,
    deleteThreadPrompt: merged.deleteThreadPrompt,
    deleteWorkspaceGroup: merged.deleteWorkspaceGroup,
    deletingWorktreeIds: merged.deletingWorktreeIds,
    diffScrollRequestId: merged.diffScrollRequestId,
    diffSource: merged.diffSource,
    directories: merged.directories,
    directoryMetadata: merged.directoryMetadata,
    dismissErrorToast: merged.dismissErrorToast,
    dismissUpdate: merged.dismissUpdate,
    doctor: merged.doctor,
    claudeDoctor: merged.claudeDoctor,
    kimiDoctor: merged.kimiDoctor,
    grokDoctor: merged.grokDoctor,
    opencodeDoctor: merged.opencodeDoctor,
    piDoctor: merged.piDoctor,
    qoderDoctor: merged.qoderDoctor,
    editorHighlightTarget: merged.editorHighlightTarget,
    editorNavigationTarget: merged.editorNavigationTarget,
    editorSplitCompanion: merged.editorSplitCompanion,
    editorSplitLayout: merged.editorSplitLayout,
    engineModelsAsOptions: merged.engineModelsAsOptions,
    engineSelectedModelIdByType: merged.engineSelectedModelIdByType,
    engineStatuses: merged.engineStatuses,
    ensureLaunchTerminal: merged.ensureLaunchTerminal,
    ensureTerminalWithTitle: merged.ensureTerminalWithTitle,
    ensureWorkspaceThreadListLoaded: merged.ensureWorkspaceThreadListLoaded,
    errorToasts: merged.errorToasts,
    exitDiffView: merged.exitDiffView,
    expandRightPanel: merged.expandRightPanel,
    expandSidebar: merged.expandSidebar,
    filePanelMode: merged.filePanelMode,
    fileReferenceMode: merged.fileReferenceMode,
    fileStatus: merged.fileStatus,
    fileTreeLoadError: merged.fileTreeLoadError,
    fileTreeSourceVersion: merged.fileTreeSourceVersion,
    files: merged.files,
    forkThreadForWorkspace: merged.forkThreadForWorkspace,
    forkSessionFromMessageForWorkspace: merged.forkSessionFromMessageForWorkspace,
    forkClaudeSessionFromMessageForWorkspace: merged.forkClaudeSessionFromMessageForWorkspace,
    getGlobalPromptsDir: merged.getGlobalPromptsDir,
    getPinTimestamp: merged.getPinTimestamp,
    getThreadRows: merged.getThreadRows,
    getWorkspaceGroupName: merged.getWorkspaceGroupName,
    getWorkspacePromptsDir: merged.getWorkspacePromptsDir,
    gitDiffListView: merged.gitDiffListView,
    gitDiffViewStyle: merged.gitDiffViewStyle,
    gitHistoryPanelHeight: merged.gitHistoryPanelHeight,
    gitIssues: merged.gitIssues,
    gitIssuesError: merged.gitIssuesError,
    gitIssuesLoading: merged.gitIssuesLoading,
    gitIssuesTotal: merged.gitIssuesTotal,
    gitLogAhead: merged.gitLogAhead,
    gitLogAheadEntries: merged.gitLogAheadEntries,
    gitLogBehind: merged.gitLogBehind,
    gitLogBehindEntries: merged.gitLogBehindEntries,
    gitLogEntries: merged.gitLogEntries,
    gitLogError: merged.gitLogError,
    gitLogLoading: merged.gitLogLoading,
    gitLogTotal: merged.gitLogTotal,
    gitLogUpstream: merged.gitLogUpstream,
    gitPanelMode: merged.gitPanelMode,
    gitPullRequestComments: merged.gitPullRequestComments,
    gitPullRequestCommentsError: merged.gitPullRequestCommentsError,
    gitPullRequestCommentsLoading: merged.gitPullRequestCommentsLoading,
    gitPullRequestDiffs: merged.gitPullRequestDiffs,
    gitPullRequests: merged.gitPullRequests,
    gitPullRequestsError: merged.gitPullRequestsError,
    gitPullRequestsLoading: merged.gitPullRequestsLoading,
    gitPullRequestsTotal: merged.gitPullRequestsTotal,
    gitRemoteUrl: merged.gitRemoteUrl,
    gitRootCandidates: merged.gitRootCandidates,
    gitRootScanDepth: merged.gitRootScanDepth,
    gitRootScanError: merged.gitRootScanError,
    gitRootScanHasScanned: merged.gitRootScanHasScanned,
    gitRootScanLoading: merged.gitRootScanLoading,
    gitStatus: merged.gitStatus,
    gitignoredDirectories: merged.gitignoredDirectories,
    gitignoredFiles: merged.gitignoredFiles,
    globalSearchFilesByWorkspace: merged.globalSearchFilesByWorkspace,
    groupedWorkspaces: merged.groupedWorkspaces,
    handleActivateFileTab: merged.handleActivateFileTab,
    handleActiveDiffPath: merged.handleActiveDiffPath,
    handleAddAgent: merged.handleAddAgent,
    handleAddCloneAgent: merged.handleAddCloneAgent,
    handleAddWorkspace: merged.handleAddWorkspace,
    handleOpenNewWindow: merged.handleOpenNewWindow,
    handleAddWorktreeAgent: merged.handleAddWorktreeAgent,
    handleAppModeChange: merged.handleAppModeChange,
    handleApplyWorktreeChanges: merged.handleApplyWorktreeChanges,
    handleApprovalBatchAccept: merged.handleApprovalBatchAccept,
    handleApprovalDecision: merged.handleApprovalDecision,
    handleApprovalRemember: merged.handleApprovalRemember,
    handleArchiveActiveThread: merged.handleArchiveActiveThread,
    handleCancelSwitchAccount: merged.handleCancelSwitchAccount,
    handleCheckoutBranch: merged.handleCheckoutBranch,
    handleCloseAllFileTabs: merged.handleCloseAllFileTabs,
    handleCloseFileTab: merged.handleCloseFileTab,
    handleCloseOtherFileTabs: merged.handleCloseOtherFileTabs,
    handleCommit: merged.handleCommit,
    handleCommitAndPush: merged.handleCommitAndPush,
    handleCommitAndSync: merged.handleCommitAndSync,
    handleCommitMessageChange: merged.handleCommitMessageChange,
    handleCopyDebug: merged.handleCopyDebug,
    handleCopyThread: merged.handleCopyThread,
    handleCreateBranch: merged.handleCreateBranch,
    handleUpdateBranch: merged.handleUpdateBranch,
    handleUpdateAllRepositories: merged.handleUpdateAllRepositories,
    handleCheckoutAllRepositories: merged.handleCheckoutAllRepositories,
    handleLoadCommonRepositoryBranches: merged.handleLoadCommonRepositoryBranches,
    handleCreatePrompt: merged.handleCreatePrompt,
    handleDebugClick: merged.handleDebugClick,
    handleDeletePrompt: merged.handleDeletePrompt,
    handleDeleteQueued: merged.handleDeleteQueued,
    handleDeleteThreadPromptCancel: merged.handleDeleteThreadPromptCancel,
    handleDeleteThreadPromptConfirm: merged.handleDeleteThreadPromptConfirm,
    handleDraftChange: merged.handleDraftChange,
    handleEditQueued: merged.handleEditQueued,
    handleEnsureWorkspaceThreadsForSettings: merged.handleEnsureWorkspaceThreadsForSettings,
    handleExitEditor: merged.handleExitEditor,
    handleGenerateCommitMessage: merged.handleGenerateCommitMessage,
    handleGitIssuesChange: merged.handleGitIssuesChange,
    handleGitPanelModeChange: merged.handleGitPanelModeChange,
    handleGitPullRequestCommentsChange: merged.handleGitPullRequestCommentsChange,
    handleGitPullRequestDiffsChange: merged.handleGitPullRequestDiffsChange,
    handleGitPullRequestsChange: merged.handleGitPullRequestsChange,
    handleInsertComposerText: merged.handleInsertComposerText,
    handleLockPanel: merged.handleLockPanel,
    handleMovePrompt: merged.handleMovePrompt,
    handleOpenDetachedFileExplorer: merged.handleOpenDetachedFileExplorer,
    handleOpenFile: merged.handleOpenFile,
    handleOpenWorkspaceFileCompare: merged.handleOpenWorkspaceFileCompare,
    handleOpenScratchFileCompare: merged.handleOpenScratchFileCompare,
    handleCloseFileCompare: merged.handleCloseFileCompare,
    handleOpenFileHistory: merged.handleOpenFileHistory,
    handleActivateGitHistoryTab: merged.handleActivateGitHistoryTab,
    handleCloseFileHistory: merged.handleCloseFileHistory,
    handleCloseOtherFileHistories: merged.handleCloseOtherFileHistories,
    handleCloseAllFileHistories: merged.handleCloseAllFileHistories,
    handleOpenMailSession: merged.handleOpenMailSession,
    handleOpenModelSettings: merged.handleOpenModelSettings,
    handleRefreshModelConfig: merged.handleRefreshModelConfig,
    handleReorderFileTabs: merged.handleReorderFileTabs,
    handleResolvedClaudeThinkingVisibleChange: merged.handleResolvedClaudeThinkingVisibleChange,
    handlePickGitRoot: merged.handlePickGitRoot,
    handlePush: merged.handlePush,
    handleRenamePromptCancel: merged.handleRenamePromptCancel,
    handleRenamePromptChange: merged.handleRenamePromptChange,
    handleRenamePromptConfirm: merged.handleRenamePromptConfirm,
    handleRenameThread: merged.handleRenameThread,
    handleRevealGeneralPrompts: merged.handleRevealGeneralPrompts,
    handleRevealWorkspacePrompts: merged.handleRevealWorkspacePrompts,
    handleRevertAllGitChanges: merged.handleRevertAllGitChanges,
    handleRevertGitFile: merged.handleRevertGitFile,
    handleRevertGitPaths: merged.handleRevertGitPaths,
    handleReviewPromptKeyDown: merged.handleReviewPromptKeyDown,
    handleSelectAgent: merged.handleSelectAgent,
    handleSelectCommit: merged.handleSelectCommit,
    handleSelectDiff: merged.handleSelectDiff,
    handleSelectModel: merged.handleSelectModel,
    handleSelectOpenAppId: merged.handleSelectOpenAppId,
    handleSelectOpenCodeAgent: merged.handleSelectOpenCodeAgent,
    handleSelectOpenCodeVariant: merged.handleSelectOpenCodeVariant,
    handleSelectStatusPanelSubagent: merged.handleSelectStatusPanelSubagent,
    handleSendPrompt: merged.handleSendPrompt,
    handleSendPromptToNewAgent: merged.handleSendPromptToNewAgent,
    handleSetAccessMode: merged.handleSetAccessMode,
    handleSetGitRoot: merged.handleSetGitRoot,
    handleStageGitAll: merged.handleStageGitAll,
    handleStageGitFile: merged.handleStageGitFile,
    handleSwitchAccount: merged.handleSwitchAccount,
    handleFuseQueued: merged.handleFuseQueued,
    handleSync: merged.handleSync,
    handleTestNotificationSound: merged.handleTestNotificationSound,
    handleToggleRuntimeConsole: merged.handleToggleRuntimeConsole,
    handleToggleTerminalPanel: merged.handleToggleTerminalPanel,
    handleUnlockPanel: merged.handleUnlockPanel,
    handleUnstageGitAll: merged.handleUnstageGitAll,
    handleUnstageGitFile: merged.handleUnstageGitFile,
    handleUnstageGitPaths: merged.handleUnstageGitPaths,
    handleUpdatePrompt: merged.handleUpdatePrompt,
    handleUserInputSubmit: merged.handleUserInputSubmit,
    handleUserInputSubmitWithPlanApply: merged.handleUserInputSubmitWithPlanApply,
    handleExitPlanModeExecute: merged.handleExitPlanModeExecute,
    handleWorkspaceDragEnter: merged.handleWorkspaceDragEnter,
    handleWorkspaceDragLeave: merged.handleWorkspaceDragLeave,
    handleWorkspaceDragOver: merged.handleWorkspaceDragOver,
    handleWorkspaceDrop: merged.handleWorkspaceDrop,
    hasActivePlan: merged.hasActivePlan,
    highlightedBranchIndex: merged.highlightedBranchIndex,
    highlightedCommitIndex: merged.highlightedCommitIndex,
    highlightedPresetIndex: merged.highlightedPresetIndex,
    hydratedThreadListWorkspaceIds: merged.hydratedThreadListWorkspaceIds,
    availableEngines: merged.availableEngines,
    interruptTurn: merged.interruptTurn,
    isCompact: merged.isCompact,
    isDeleteThreadPromptBusy: merged.isDeleteThreadPromptBusy,
    isEditorFileMaximized: merged.isEditorFileMaximized,
    isFilesLoading: merged.isFilesLoading,
    isMacDesktop: merged.isMacDesktop,
    isModelConfigRefreshing: merged.isModelConfigRefreshing,
    isPanelLocked: merged.isPanelLocked,
    isPhone: merged.isPhone,
    isPlanMode: merged.isPlanMode,
    isPlanPanelDismissed: merged.isPlanPanelDismissed,
    isSearchPaletteOpen: merged.isSearchPaletteOpen,
    isTablet: merged.isTablet,
    isThreadAutoNaming: merged.isThreadAutoNaming,
    isThreadPinned: merged.isThreadPinned,
    isWindowsDesktop: merged.isWindowsDesktop,
    isWorkspaceDropActive: merged.isWorkspaceDropActive,
    isWorktreeWorkspace: merged.isWorktreeWorkspace,
    launchScriptState: merged.launchScriptState,
    launchScriptsState: merged.launchScriptsState,
    listThreadsForWorkspaceTracked: merged.listThreadsForWorkspaceTracked,
    liveEditPreviewEnabled: merged.liveEditPreviewEnabled,
    loadOlderThreadsForWorkspace: merged.loadOlderThreadsForWorkspace,
    lockLiveSessions: merged.lockLiveSessions,
    models: merged.models,
    moveWorkspaceGroup: merged.moveWorkspaceGroup,
    handleOpenClaudeTui: merged.handleOpenClaudeTui,
    normalizePath: merged.normalizePath,
    onCloseTerminal: merged.onCloseTerminal,
    onDebugPanelResizeStart: merged.onDebugPanelResizeStart,
    onGitHistoryPanelResizeStart: merged.onGitHistoryPanelResizeStart,
    onNewTerminal: merged.onNewTerminal,
    onPlanPanelResizeStart: merged.onPlanPanelResizeStart,
    onRightPanelResizeStart: merged.onRightPanelResizeStart,
    onSelectTerminal: merged.onSelectTerminal,
    onSidebarResizeStart: merged.onSidebarResizeStart,
    onTerminalPanelResizeStart: merged.onTerminalPanelResizeStart,
    onTextareaHeightChange: merged.onTextareaHeightChange,
    openAppIconById: merged.openAppIconById,
    openCodeAgents: merged.openCodeAgents,
    openDeleteThreadPrompt: merged.openDeleteThreadPrompt,
    openFileTabs: merged.openFileTabs,
    openPlanPanel: merged.openPlanPanel,
    openReleaseNotes: merged.openReleaseNotes,
    openSettings: merged.openSettings,
    persistComposerSelectionForThread: merged.persistComposerSelectionForThread,
    pickImages: merged.pickImages,
    pinThread: merged.pinThread,
    pinnedThreadsVersion: merged.pinnedThreadsVersion,
    planPanelHeight: merged.planPanelHeight,
    prefillDraft: merged.prefillDraft,
    prompts: merged.prompts,
    pushError: merged.pushError,
    pushLoading: merged.pushLoading,
    queueGitStatusRefresh: merged.queueGitStatusRefresh,
    queueSaveSettings: merged.queueSaveSettings,
    recentThreads: merged.recentThreads,
    reduceTransparency: merged.reduceTransparency,
    windowTransparencyEnabled: merged.windowTransparencyEnabled,
    windowOpacity: merged.windowOpacity,
    refreshAccountRateLimits: merged.refreshAccountRateLimits,
    refreshEngines: merged.refreshEngines,
    refreshFiles: merged.refreshFiles,
    refreshGitDiffs: merged.refreshGitDiffs,
    refreshGitLog: merged.refreshGitLog,
    refreshThread: merged.refreshThread,
    releaseNotesActiveIndex: merged.releaseNotesActiveIndex,
    releaseNotesEntries: merged.releaseNotesEntries,
    releaseNotesError: merged.releaseNotesError,
    releaseNotesLoading: merged.releaseNotesLoading,
    releaseNotesOpen: merged.releaseNotesOpen,
    removeImage: merged.removeImage,
    removeImagesForThread: merged.removeImagesForThread,
    removeThread: merged.removeThread,
    removeThreads: merged.removeThreads,
    removeWorkspace: merged.removeWorkspace,
    removeWorktree: merged.removeWorktree,
    renamePrompt: merged.renamePrompt,
    renameWorkspaceGroup: merged.renameWorkspaceGroup,
    renameWorktreeUpstream: merged.renameWorktreeUpstream,
    renameWorktreeUpstreamPrompt: merged.renameWorktreeUpstreamPrompt,
    resetGitHubPanelState: merged.resetGitHubPanelState,
    resetSoloSplitToHalf: merged.resetSoloSplitToHalf,
    resetWorkspaceThreads: merged.resetWorkspaceThreads,
    resolveCloneProjectContext: merged.resolveCloneProjectContext,
    resolveCanonicalThreadId: merged.resolveCanonicalThreadId,
    resolveComposerSelectionForThread: merged.resolveComposerSelectionForThread,
    resolveOpenCodeAgentForThread: merged.resolveOpenCodeAgentForThread,
    resolveOpenCodeVariantForThread: merged.resolveOpenCodeVariantForThread,
    restartTerminalSession: merged.restartTerminalSession,
    retryReleaseNotesLoad: merged.retryReleaseNotesLoad,
    reviewPrompt: merged.reviewPrompt,
    rightPanelCollapsed: merged.rightPanelCollapsed,
    rightPanelWidth: merged.rightPanelWidth,
    scaleShortcutText: merged.scaleShortcutText,
    scaleShortcutTitle: merged.scaleShortcutTitle,
    scanGitRoots: merged.scanGitRoots,
    searchContentFilters: merged.searchContentFilters,
    searchApiHydrationStatus: merged.searchApiHydrationStatus,
    searchFileHydrationStatus: merged.searchFileHydrationStatus,
    searchPaletteQuery: merged.searchPaletteQuery,
    searchPaletteSelectedIndex: merged.searchPaletteSelectedIndex,
    searchResults: merged.searchResults,
    searchScope: merged.searchScope,
    selectBranch: merged.selectBranch,
    selectBranchAtIndex: merged.selectBranchAtIndex,
    selectCommit: merged.selectCommit,
    selectCommitAtIndex: merged.selectCommitAtIndex,
    selectHome: merged.selectHome,
    selectWorkspace: merged.selectWorkspace,
    selectedAgent: merged.selectedAgent,
    selectedCommitSha: merged.selectedCommitSha,
    selectedDiffPath: merged.selectedDiffPath,
    selectedAgentRef: merged.selectedAgentRef,
    selectedOpenCodeAgent: merged.selectedOpenCodeAgent,
    selectedOpenCodeVariant: merged.selectedOpenCodeVariant,
    selectedPullRequest: merged.selectedPullRequest,
    sendUserMessageToThread: merged.sendUserMessageToThread,
    setActiveEditorLineRange: merged.setActiveEditorLineRange,
    setActiveEngine: merged.setActiveEngine,
    setActiveTab: merged.setActiveTab,
    setActiveThreadId: merged.setActiveThreadId,
    setActiveWorkspaceId: merged.setActiveWorkspaceId,
    setAppMode: merged.setAppMode,
    setAppSettings: merged.setAppSettings,
    setCenterMode: merged.setCenterMode,
    setComposerInsert: merged.setComposerInsert,
    setDiffSource: merged.setDiffSource,
    setEditorSplitCompanion: merged.setEditorSplitCompanion,
    setEditorSplitLayout: merged.setEditorSplitLayout,
    setFilePanelMode: merged.setFilePanelMode,
    setFileReferenceMode: merged.setFileReferenceMode,
    setGitDiffListView: merged.setGitDiffListView,
    setGitDiffViewStyle: merged.setGitDiffViewStyle,
    setGitPanelMode: merged.setGitPanelMode,
    setGitRootScanDepth: merged.setGitRootScanDepth,
    setHighlightedBranchIndex: merged.setHighlightedBranchIndex,
    setHighlightedCommitIndex: merged.setHighlightedCommitIndex,
    setHighlightedPresetIndex: merged.setHighlightedPresetIndex,
    setIsEditorFileMaximized: merged.setIsEditorFileMaximized,
    setIsSearchPaletteOpen: merged.setIsSearchPaletteOpen,
    setLiveEditPreviewEnabled: merged.setLiveEditPreviewEnabled,
    setPrefillDraft: merged.setPrefillDraft,
    setReduceTransparency: merged.setReduceTransparency,
    setWindowTransparencyEnabled: merged.setWindowTransparencyEnabled,
    setWindowOpacity: merged.setWindowOpacity,
    setSearchContentFilters: merged.setSearchContentFilters,
    setSearchPaletteQuery: merged.setSearchPaletteQuery,
    setSearchPaletteSelectedIndex: merged.setSearchPaletteSelectedIndex,
    setSearchScope: merged.setSearchScope,
    setSelectedCommitSha: merged.setSelectedCommitSha,
    setSelectedDiffPath: merged.setSelectedDiffPath,
    setSelectedPullRequest: merged.setSelectedPullRequest,
    setHomeOpen: merged.setHomeOpen,
    setWorkspaceHomeWorkspaceId: merged.setWorkspaceHomeWorkspaceId,
    settingsHighlightTarget: merged.settingsHighlightTarget,
    settingsOpen: merged.settingsOpen,
    settingsSection: merged.settingsSection,
    loadingProgressDialog: merged.loadingProgressDialog,
    dismissLoadingProgressDialog: merged.dismissLoadingProgressDialog,
    shouldLoadDiffs: merged.shouldLoadDiffs,
    shouldLoadGitHubPanelData: merged.shouldLoadGitHubPanelData,
    showLoadingProgressDialog: merged.showLoadingProgressDialog,
    hideLoadingProgressDialog: merged.hideLoadingProgressDialog,
    showDebugButton: merged.showDebugButton,
    showGitHistory: merged.showGitHistory,
    showExtensions: merged.showExtensions,
    showHome: merged.showHome,
    showNextReleaseNotes: merged.showNextReleaseNotes,
    showPresetStep: merged.showPresetStep,
    showPreviousReleaseNotes: merged.showPreviousReleaseNotes,
    showWorkspaceHome: merged.showWorkspaceHome,
    sidebarCollapsed: merged.sidebarCollapsed,
    sidebarWidth: merged.sidebarWidth,
    skills: merged.skills,
    startCompact: merged.startCompact,
    startThreadForWorkspace: merged.startThreadForWorkspace,
    startSharedSessionForWorkspace: merged.startSharedSessionForWorkspace,
    startUpdate: merged.startUpdate,
    syncError: merged.syncError,
    syncLoading: merged.syncLoading,
    t: merged.t,
    tabletTab: merged.tabletTab,
    terminalOpen: merged.terminalOpen,
    terminalPanelHeight: merged.terminalPanelHeight,
    terminalState: merged.terminalState,
    terminalTabs: merged.terminalTabs,
    textareaHeight: merged.textareaHeight,
    threadItemsByThread: merged.threadItemsByThread,
    threadListCursorByWorkspace: merged.threadListCursorByWorkspace,
    threadListLoadingByWorkspace: merged.threadListLoadingByWorkspace,
    threadListPagingByWorkspace: merged.threadListPagingByWorkspace,
    threadParentById: merged.threadParentById,
    threadStatusById: merged.threadStatusById,
    historyLoadingByThreadId: merged.historyLoadingByThreadId,
    historyLoadingProgressByThreadId: merged.historyLoadingProgressByThreadId,
    historyRestoredAtMsByThread: merged.historyRestoredAtMsByThread,
    threadsByWorkspace: merged.threadsByWorkspace,
    toggleCompletionEmailIntent: merged.toggleCompletionEmailIntent,
    triggerAutoThreadTitle: merged.triggerAutoThreadTitle,
    ungroupedLabel: merged.ungroupedLabel,
    unpinThread: merged.unpinThread,
    updateCloneCopyName: merged.updateCloneCopyName,
    updateCustomInstructions: merged.updateCustomInstructions,
    updateWorkspaceCodexBin: merged.updateWorkspaceCodexBin,
    updateWorkspaceSettings: merged.updateWorkspaceSettings,
    updateWorktreeBaseRef: merged.updateWorktreeBaseRef,
    updateWorktreeBranch: merged.updateWorktreeBranch,
    updateWorktreePublishToOrigin: merged.updateWorktreePublishToOrigin,
    updateWorktreeSetupScript: merged.updateWorktreeSetupScript,
    updaterState: merged.updaterState,
    useSuggestedCloneCopiesFolder: merged.useSuggestedCloneCopiesFolder,
    userInputRequests: merged.userInputRequests,
    workspaceActivity: merged.workspaceActivity,
    workspaceDropTargetRef: merged.workspaceDropTargetRef,
    workspaceGroups: merged.workspaceGroups,
    homeWorkspaceSelectedId: merged.homeWorkspaceSelectedId,
    workspaces: merged.workspaces,
    workspacesById: merged.workspacesById,
    workspacesByPath: merged.workspacesByPath,
    worktreeApplyError: merged.worktreeApplyError,
    worktreeApplyLoading: merged.worktreeApplyLoading,
    worktreeApplySuccess: merged.worktreeApplySuccess,
    worktreeCreateResult: merged.worktreeCreateResult,
    worktreeLabel: merged.worktreeLabel,
    worktreePrompt: merged.worktreePrompt,
    worktreeRename: merged.worktreeRename,
    runtimeRunState: merged.runtimeRunState,
    effectiveModels: merged.effectiveModels,
    effectiveReasoningSupported: merged.effectiveReasoningSupported,
    effectiveSelectedModel: merged.effectiveSelectedModel,
    effectiveSelectedModelId: merged.effectiveSelectedModelId,
    providerModelCatalogs: merged.providerModelCatalogs,
    refreshEngineModels: merged.refreshEngineModels,
    resolvedEffort: merged.resolvedEffort,
    resolvedModel: merged.resolvedModel,
    setSelectedModelId: merged.setSelectedModelId,
    applySelectedCollaborationMode: merged.applySelectedCollaborationMode,
    collaborationModePayload: merged.collaborationModePayload,
    collaborationModes: merged.collaborationModes,
    collaborationModesEnabled: merged.collaborationModesEnabled,
    collaborationRuntimeModeByThread: merged.collaborationRuntimeModeByThread,
    collaborationUiModeByThread: merged.collaborationUiModeByThread,
    handleCollaborationModeResolved: merged.handleCollaborationModeResolved,
    resolveCollaborationRuntimeMode: merged.resolveCollaborationRuntimeMode,
    resolveCollaborationUiMode: merged.resolveCollaborationUiMode,
    selectedCollaborationMode: merged.selectedCollaborationMode,
    selectedCollaborationModeId: merged.selectedCollaborationModeId,
    setCodexCollaborationMode: merged.setCodexCollaborationMode,
    setCollaborationRuntimeModeByThread: merged.setCollaborationRuntimeModeByThread,
    setCollaborationUiModeByThread: merged.setCollaborationUiModeByThread,
    setSelectedCollaborationModeId: merged.setSelectedCollaborationModeId,
    effectiveReasoningOptions: merged.effectiveReasoningOptions,
    effectiveSelectedEffort: merged.effectiveSelectedEffort,
    handleSelectComposerEffort: merged.handleSelectComposerEffort,
    GitHubPanelData,
    SettingsView,
    sessionRadarRunningSessions: sessionRadarFeed.runningSessions,
    sessionRadarRecentCompletedSessions: sessionRadarFeed.recentCompletedSessions,
    runningSessionCountByWorkspaceId: sessionRadarFeed.runningCountByWorkspaceId,
    recentCompletedSessionCountByWorkspaceId: sessionRadarFeed.recentCountByWorkspaceId,
  } as any);

  const runtimeThreadProviderValue = useMemoizedRuntimeThreadProviderValue({
    activeItems: runtime.activeItems as any,
    activePlan: runtime.activePlan as any,
    activeRateLimits: runtime.activeRateLimits as any,
    activeTokenUsage: runtime.activeTokenUsage as any,
    activeTurnId: runtime.activeTurnId as any,
    canInterrupt: runtime.canInterrupt as boolean,
    isProcessing: runtime.isProcessing as boolean,
    isReviewing: runtime.isReviewing as boolean,
    timelinePlan: runtime.timelinePlan as any,
    interruptTurn: runtime.interruptTurn as any,
    runtimeThreadBoundary: runtime.runtimeThreadBoundary as any,
  });
  const composerProviderValue = useMemoizedComposerProviderValue({
    handleSend: composer.handleSend as any,
    handleDraftChange: composer.handleDraftChange as any,
    getActiveDraft: composer.getActiveDraft as any,
    queueMessage: composer.queueMessage as any,
    clearActiveImages: composer.clearActiveImages as any,
    activeImages: composer.activeImages as any,
    composerInsert: composer.composerInsert as any,
    setComposerInsert: composer.setComposerInsert as any,
    prefillDraft: composer.prefillDraft as any,
    setPrefillDraft: composer.setPrefillDraft as any,
    interruptTurn: runtime.interruptTurn as any,
    canInterrupt: runtime.canInterrupt as boolean,
  });
  const layoutChromeProviderValue = useMemoizedLayoutChromeProviderValue({
    appMode: session.appMode as any,
    centerMode: git.centerMode as any,
    activeTab: session.activeTab as any,
    accessMode: catalog.accessMode as any,
    filePanelMode: git.filePanelMode as any,
    gitPanelMode: git.gitPanelMode as any,
    sidebarCollapsed: session.sidebarCollapsed as any,
    sidebarWidth: session.sidebarWidth as any,
    rightPanelCollapsed: session.rightPanelCollapsed as any,
    rightPanelWidth: session.rightPanelWidth as any,
    isPanelLocked: session.isPanelLocked as any,
    expandSidebar: session.expandSidebar as any,
    collapseSidebar: session.collapseSidebar as any,
    expandRightPanel: session.expandRightPanel as any,
    collapseRightPanel: session.collapseRightPanel as any,
    setAppMode: session.setAppMode as any,
    setCenterMode: git.setCenterMode as any,
    setActiveTab: session.setActiveTab as any,
    setFilePanelMode: git.setFilePanelMode as any,
    setGitPanelMode: git.setGitPanelMode as any,
  });

  const quick = (flows.quickSwitcherSection ?? EMPTY_HOST_SECTION) as Record<string, unknown>;
  const searchAndComposerInput = {
      identity: {
        activeWorkspace: session.activeWorkspace,
        activeWorkspaceId: session.activeWorkspaceId,
        workspacesById: session.workspacesById,
        appSettings: session.appSettings,
        isCompact: session.isCompact,
      },
      send: {
        activeWorkspace: session.activeWorkspace,
        clearActiveImages: composer.clearActiveImages,
        connectWorkspace: session.connectWorkspace,
        gitPullRequestDiffs: git.gitPullRequestDiffs,
        handleSend: composer.handleSend,
        queueMessage: composer.queueMessage,
        selectedPullRequest: git.selectedPullRequest,
        sendUserMessageToThread: runtime.sendUserMessageToThread,
        startThreadForWorkspace: runtime.startThreadForWorkspace,
        canInterrupt: runtime.canInterrupt,
        interruptTurn: runtime.interruptTurn,
        getActiveDraft: composer.getActiveDraft,
        handleDraftChange: composer.handleDraftChange,
        handleAddAgent: flows.handleAddAgent,
      },
      navigation: {
        filePanelMode: git.filePanelMode,
        gitPanelMode: git.gitPanelMode,
        setCenterMode: git.setCenterMode,
        setGitPanelMode: git.setGitPanelMode,
        setPrefillDraft: composer.setPrefillDraft,
        centerMode: git.centerMode,
        selectWorkspace: flows.selectWorkspace,
        setActiveTab: session.setActiveTab,
        setActiveThreadId: runtime.setActiveThreadId,
        setAppMode: session.setAppMode,
        setDiffSource: git.setDiffSource,
        exitDiffView: flows.exitDiffView,
        handleOpenFile: git.handleOpenFile,
      },
      search: {
        isSearchPaletteOpen: session.isSearchPaletteOpen,
        searchPaletteQuery: session.searchPaletteQuery,
        searchContentFilters: session.searchContentFilters,
        searchResults: flows.searchResults,
        searchScope: session.searchScope,
        setIsSearchPaletteOpen: session.setIsSearchPaletteOpen,
        setSearchContentFilters: session.setSearchContentFilters,
        setSearchPaletteQuery: session.setSearchPaletteQuery,
        setSearchPaletteSelectedIndex: session.setSearchPaletteSelectedIndex,
        setSearchScope: session.setSearchScope,
        setSelectedCommitSha: git.setSelectedCommitSha,
        setSelectedDiffPath: git.setSelectedDiffPath,
        setSelectedPullRequest: git.setSelectedPullRequest,
        activeEditorFilePath: git.activeEditorFilePath,
      },
      chrome: {
        closeQuickSwitcher: quick.closeQuickSwitcher,
        handleOpenQuickSwitcher: quick.handleOpenQuickSwitcher,
        handleQuickSwitcherNavigate: quick.handleQuickSwitcherNavigate,
        handleQuickSwitcherSelectFile: quick.handleQuickSwitcherSelectFile,
        handleQuickSwitcherSelectSession: quick.handleQuickSwitcherSelectSession,
        isQuickSwitcherOpen: quick.isQuickSwitcherOpen,
        quickSwitcherRecentFileGroups: quick.quickSwitcherRecentFileGroups,
        quickSwitcherRunningSessions: quick.quickSwitcherRunningSessions,
        quickSwitcherSessionGroups: quick.quickSwitcherSessionGroups,
        increaseUiScale: session.increaseUiScale,
        decreaseUiScale: session.decreaseUiScale,
        resetUiScale: session.resetUiScale,
      },
  };
  // The object above is intentionally reconstructed for the static contract
  // checker; slice identities are the real memoization boundary.
  const stableSearchAndComposerInput = useMemo(
    () => searchAndComposerInput,
    [composer, flows, git, quick, runtime, session],
  );

  return {
    runtimeThreadProviderValue,
    composerProviderValue,
    layoutChromeProviderValue,
    appShellDomainContexts,
    searchAndComposerInput: stableSearchAndComposerInput,
  };
}
