// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    appearance: {
      "motionPaused": "System reduced motion is active. Select On and save to play the effect.",
      "motionOn": "On",
      "motionSystem": "Follow system",
      "motionOff": "Off",
      "cancel": "Cancel changes",
      "customize": "Home appearance",
      "description": "Make this space yours. Leave the title empty to use the default.",
      "title": "Title",
      "font": "Title style",
      "system": "System",
      "serif": "Serif",
      "mono": "Monospace",
      "logo": "Custom logo",
      "logoHint": "PNG, JPEG or WebP · up to 512 KB and 2048 × 2048. Stored locally.",
      "engineLogo": "Use engine logo",
      "loading": "Loading image…",
      "logoError": "Choose a valid PNG, JPEG or WebP under 512 KB and 2048 × 2048.",
      "particles": "Particle effect",
      "density": "Particle density",
      "dense": "Dense",
      "balanced": "Balanced",
      "sparse": "Sparse",
      "color": "Particle color",
      "theme": "Follow theme",
      "customColor": "Custom color",
      "motionHint": "Move the pointer over the title and logo to scatter particles; move away to restore them. On overrides system reduced motion.",
      "reset": "Reset defaults",
      "apply": "Save"
    },
    "badge": "Inicio de chat con contexto del espacio de trabajo",
    "minimalTitle": "Crea lo que sea",
    "announcementTag": "Nuevo",
    "announcementText": "Explora plantillas de landing, tarjetas de flujo de trabajo y prompts iniciales",
    "announcementAction": "Descubrir",
    "title": "Agente de ccgui, facilita el trabajo",
    "titleLineOne": "Pulsa Intro",
    "titleLineTwo": "Crea apps más rápido",
    "subtitle": "Conserva el editor que ya conoces, añade a su alrededor un ritmo de landing más potente y pasa a la ejecución real con menos fricción de configuración.",
    "promptPlaceholder": "Describe tu objetivo, por ejemplo: Genera notas de la versión para este repositorio e incluye comprobaciones de riesgo.",
    "pathResolving": "Resolviendo la ruta predeterminada del proyecto...",
    "workspaceSearchPlaceholder": "Buscar proyectos",
    "addWorkspaceAction": "Añadir nuevo proyecto",
    "workspaceNoMatch": "No se encontraron proyectos",
    "loadingRecentAgents": "Cargando trabajo reciente",
    "recentConversations": "Conversaciones recientes",
    "quickActions": "Acciones rápidas",
    "placeholderHint": "Por ahora, estos puntos de entrada son marcadores visuales.",
    "placeholderSelected": "{{label}} estará disponible próximamente.",
    "seeAll": "Ver todo",
    "navPrev": "Tarjetas anteriores",
    "navNext": "Tarjetas siguientes",
    "comingSoon": "Próximamente",
    "tabs": {
      "templates": "Plantillas",
      "workflows": "Flujos de trabajo"
    },
    "quick": {
      "plan": "Planificar desde un brief",
      "doc": "Documentos",
      "release": "Notas de versión",
      "review": "Revisar repositorio",
      "spec": "Redactar especificación"
    },
    "cards": {
      "website": {
        "title": "Kit de lanzamiento de sitio web",
        "description": "Diseño de hero, estructura y texto inicial para una página de lanzamiento pulida."
      },
      "creator": {
        "title": "Panel de creador",
        "description": "Un centro de control centrado en analíticas para contenido, tráfico y prompts."
      },
      "audio": {
        "title": "Landing de audio",
        "description": "Gradientes suaves y métricas llamativas para lanzamientos de música, pódcasts o medios."
      },
      "editorial": {
        "title": "Manifiesto editorial",
        "description": "Tipografía de póster para campañas, declaraciones y escaparates de marca."
      },
      "release": {
        "title": "Lista de comprobación de la versión",
        "description": "Un traspaso por fases para cambios, verificación, notas y seguimiento del despliegue."
      },
      "research": {
        "title": "Sprint de investigación",
        "description": "Recopila preguntas, obtén hallazgos de fuentes y sintetízalos en las próximas acciones."
      },
      "debug": {
        "title": "Mesa de depuración",
        "description": "Clasificar logs, acotar regresiones y documentar correcciones verificadas."
      },
      "content": {
        "title": "Pipeline de contenido",
        "description": "Brief, borrador, revisión y publicación con puntos de control consistentes."
      }
    }
  }
};

export default homeChat;
