import type { ConversationItem } from "../../../types";
import {
  normalizeItem,
  prepareThreadItems,
  upsertItem,
} from "../../../utils/threadItems";
import { isOptimisticUserMessageId } from "../utils/queuedHandoffBubble";
import { isIncrementalDerivationEnabled } from "../utils/realtimePerfFlags";
import { isProcessingGeneratedImageItem } from "../utils/generatedImagePlaceholder";
import { replaceMatchingProcessingGeneratedImage } from "../utils/generatedImagePlaceholderMatching";
import {
  insertGeneratedImagesAfterAnchors,
  replaceOptimisticUserAndExtractAnchoredGeneratedImages,
} from "./threadReducerOptimisticUserReconciliation";
import {
  findAssistantMessageIndexById,
  isAssistantMessageItem,
  isUserMessageItem,
  resolveLiveReasoningItemId,
} from "./threadReducerCoreHelpers";
import {
  conversationItemsShallowEqual,
  findEquivalentAssistantSnapshotIndex,
} from "./threadReducerEqualityGuards";
import {
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  findMatchingReview,
  isDuplicateReviewById,
} from "./threadReducerReviewItems";
import {
  findDuplicateReasoningSnapshotIndex,
  mergeCompletedAgentText,
  mergeReasoningSnapshotTextForThread,
  normalizeReasoningReadableText,
} from "./threadReducerTextMerge";
import {
  findEquivalentCodexAssistantMessageIndex,
  shouldDeduplicateCodexAssistantMessages,
} from "./useThreadsReducerAssistantDedup";
import {
  extractRenameTextFromUserItem,
  looksAutoGeneratedThreadName,
} from "./threadReducerThreadNaming";
import type { ThreadAction, ThreadState } from "./threadReducerTypes";

const INCREMENTAL_DERIVATION_ENABLED = isIncrementalDerivationEnabled();

type GeneratedImageItem = Extract<ConversationItem, { kind: "generatedImage" }>;

export function reduceUpsertItem(
  state: ThreadState,
  action: Extract<ThreadAction, { type: "upsertItem" }>,
): ThreadState {
  let list = state.itemsByThread[action.threadId] ?? [];
  const rawAssistantSnapshotText =
    action.item.kind === "message" && action.item.role === "assistant"
      ? action.item.text
      : "";
  const item = normalizeItem(action.item);
  const isUserMessage = isUserMessageItem(item);
  const isOptimisticUser = isUserMessage && isOptimisticUserMessageId(item.id);
  let generatedImagesToReinsertAfterUser: GeneratedImageItem[] = [];
  let inheritedProviderRetry: Pick<
    Extract<ConversationItem, { kind: "message" }>,
    "originKind" | "providerRetryAttempt" | "providerRetryAtMs"
  > | null = null;
  if (isUserMessage && !isOptimisticUser) {
    inheritedProviderRetry =
      list.find(
        (entry): entry is Extract<ConversationItem, { kind: "message" }> =>
          isUserMessageItem(entry) &&
          isOptimisticUserMessageId(entry.id) &&
          entry.originKind === "shared-provider-retry",
      ) ?? null;
    const optimisticReplacement =
      replaceOptimisticUserAndExtractAnchoredGeneratedImages(list, item);
    list = optimisticReplacement.items;
    generatedImagesToReinsertAfterUser =
      optimisticReplacement.generatedImagesToReinsert;
  }
  const hadUserMessage = isUserMessage
    ? list.some((entry) => extractRenameTextFromUserItem(entry).length > 0)
    : false;
  const renameText = isUserMessage ? extractRenameTextFromUserItem(item) : "";
  if (
    item.kind === "review" &&
    item.state === "started" &&
    !item.id.startsWith("review-start-")
  ) {
    list = dropLatestLocalReviewStart(list);
  }
  if (item.kind === "review" && isDuplicateReviewById(list, item)) {
    return state;
  }
  if (item.kind === "review") {
    const existing = findMatchingReview(list, item);
    if (existing && existing.id !== item.id) {
      return state;
    }
  }
  let nextItem = ensureUniqueReviewId(list, item);
  if (
    inheritedProviderRetry &&
    nextItem.kind === "message" &&
    nextItem.originKind !== "shared-provider-retry"
  ) {
    nextItem = {
      ...nextItem,
      originKind: "shared-provider-retry",
      providerRetryAttempt: inheritedProviderRetry.providerRetryAttempt,
      providerRetryAtMs: inheritedProviderRetry.providerRetryAtMs,
    };
  }
  let didMergeEquivalentAssistantSnapshot = false;
  if (
    nextItem.kind === "generatedImage" &&
    !isProcessingGeneratedImageItem(nextItem)
  ) {
    const replacedList = replaceMatchingProcessingGeneratedImage(
      list,
      nextItem,
    );
    if (replacedList) {
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(replacedList),
        },
      };
    }
  }
  if (nextItem.kind === "reasoning") {
    const segmentedReasoningId = resolveLiveReasoningItemId(
      state,
      action.threadId,
      nextItem.id,
    );
    if (segmentedReasoningId !== nextItem.id) {
      nextItem = { ...nextItem, id: segmentedReasoningId };
    }
    const existingReasoning = list.find(
      (entry): entry is Extract<ConversationItem, { kind: "reasoning" }> =>
        entry.id === nextItem.id && entry.kind === "reasoning",
    );
    if (existingReasoning) {
      const existingSummary = normalizeReasoningReadableText(
        existingReasoning.summary,
      );
      const incomingSummary = normalizeReasoningReadableText(nextItem.summary);
      const existingContent = normalizeReasoningReadableText(
        existingReasoning.content,
      );
      const incomingContent = normalizeReasoningReadableText(nextItem.content);
      nextItem = {
        ...nextItem,
        summary: mergeReasoningSnapshotTextForThread(
          action.threadId,
          existingSummary,
          incomingSummary,
        ),
        content: mergeReasoningSnapshotTextForThread(
          action.threadId,
          existingContent,
          incomingContent,
        ),
      };
    } else {
      const normalizedIncoming = {
        ...nextItem,
        summary: normalizeReasoningReadableText(nextItem.summary),
        content: normalizeReasoningReadableText(nextItem.content),
      };
      const duplicateIndex = findDuplicateReasoningSnapshotIndex(
        list,
        normalizedIncoming,
      );
      if (duplicateIndex >= 0 && list[duplicateIndex]?.kind === "reasoning") {
        const duplicate = list[duplicateIndex] as Extract<
          ConversationItem,
          { kind: "reasoning" }
        >;
        nextItem = {
          ...normalizedIncoming,
          id: duplicate.id,
          summary: mergeReasoningSnapshotTextForThread(
            action.threadId,
            duplicate.summary,
            normalizedIncoming.summary,
          ),
          content: mergeReasoningSnapshotTextForThread(
            action.threadId,
            duplicate.content,
            normalizedIncoming.content,
          ),
        };
      } else {
        nextItem = normalizedIncoming;
      }
    }
  }
  if (
    nextItem.kind === "message" &&
    nextItem.role === "assistant" &&
    shouldDeduplicateCodexAssistantMessages({
      threadsByWorkspace: state.threadsByWorkspace,
      workspaceId: action.workspaceId,
      threadId: action.threadId,
    }) &&
    findAssistantMessageIndexById(list, nextItem.id) < 0
  ) {
    const incomingAssistantText = rawAssistantSnapshotText || nextItem.text;
    const codexEquivalentAssistantIndex =
      findEquivalentCodexAssistantMessageIndex(
        list,
        incomingAssistantText,
        "settled",
      );
    const equivalentAssistantIndex =
      codexEquivalentAssistantIndex >= 0
        ? codexEquivalentAssistantIndex
        : findEquivalentAssistantSnapshotIndex(list, incomingAssistantText);
    const equivalentAssistant =
      equivalentAssistantIndex >= 0
        ? list[equivalentAssistantIndex]
        : undefined;
    if (isAssistantMessageItem(equivalentAssistant)) {
      const mergedText = mergeCompletedAgentText(
        equivalentAssistant.text,
        incomingAssistantText,
      );
      list = [
        ...list.slice(0, equivalentAssistantIndex),
        {
          ...equivalentAssistant,
          ...nextItem,
          id: equivalentAssistant.id,
          text: mergedText,
        },
        ...list.slice(equivalentAssistantIndex + 1),
      ];
      nextItem = list[equivalentAssistantIndex] ?? nextItem;
      didMergeEquivalentAssistantSnapshot = true;
    }
  }
  if (
    INCREMENTAL_DERIVATION_ENABLED &&
    !didMergeEquivalentAssistantSnapshot &&
    generatedImagesToReinsertAfterUser.length === 0 &&
    !isUserMessage
  ) {
    const existingIndex = list.findIndex(
      (entry) => entry.id === nextItem.id && entry.kind === nextItem.kind,
    );
    if (existingIndex >= 0) {
      const existingSlot = list[existingIndex];
      if (existingSlot !== undefined) {
        // mirror upsertItem's merge semantics inline so we can compare
        // the merged slot against the existing reference
        const mergedSlot = (() => {
          if (existingSlot.kind === "tool" && nextItem.kind === "tool") {
            // tool items are handled inside prepareThreadItems via
            // mergeToolItemPreservingSnapshot; skip the fast path.
            return null;
          }
          if (
            existingSlot.kind === "generatedImage" &&
            nextItem.kind === "generatedImage"
          ) {
            return {
              ...existingSlot,
              ...nextItem,
              status:
                nextItem.status === "completed" ||
                nextItem.status === "degraded"
                  ? nextItem.status
                  : existingSlot.status,
              promptText: nextItem.promptText || existingSlot.promptText,
              fallbackText: nextItem.fallbackText || existingSlot.fallbackText,
              anchorUserMessageId:
                nextItem.anchorUserMessageId ??
                existingSlot.anchorUserMessageId,
              images:
                nextItem.images.length > 0
                  ? nextItem.images
                  : existingSlot.images,
            };
          }
          return { ...existingSlot, ...nextItem } as ConversationItem;
        })();
        if (
          mergedSlot !== null &&
          conversationItemsShallowEqual(existingSlot, mergedSlot)
        ) {
          return state;
        }
      }
    }
  }
  let nextList = upsertItem(list, nextItem);
  if (generatedImagesToReinsertAfterUser.length > 0) {
    nextList = insertGeneratedImagesAfterAnchors(
      nextList,
      generatedImagesToReinsertAfterUser,
    );
  }
  const updatedItems = prepareThreadItems(nextList);
  let nextThreadsByWorkspace = state.threadsByWorkspace;
  if (isUserMessage) {
    const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
    const textValue = renameText;
    const updatedThreads = threads.map((thread) => {
      if (thread.id !== action.threadId) {
        return thread;
      }
      const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
      const shouldRename =
        !hadUserMessage &&
        textValue.length > 0 &&
        looksAutoGenerated &&
        !action.hasCustomName;
      const nextName = shouldRename ? textValue : thread.name;
      return { ...thread, name: nextName };
    });
    const bumpedThreads = updatedThreads.length
      ? [
          ...updatedThreads.filter((thread) => thread.id === action.threadId),
          ...updatedThreads.filter((thread) => thread.id !== action.threadId),
        ]
      : updatedThreads;
    nextThreadsByWorkspace = {
      ...state.threadsByWorkspace,
      [action.workspaceId]: bumpedThreads,
    };
  }
  return {
    ...state,
    itemsByThread: {
      ...state.itemsByThread,
      [action.threadId]: updatedItems,
    },
    threadsByWorkspace: nextThreadsByWorkspace,
  };
}
